### ISSUE TITLE
Gibson Assembly compatibility with sources coming from restriction

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_backend#145]
I have tried to use Gibson to assemble two PCR fragments with a plasmid linearized by digestion with two restriction enzymes, but SYC does not find a compatible assembly. However, when I manually type the digested fragments without overhangs, it works.

I have not tested it further, so I wonder whether it is a specific problem to this particular example or a general lack of support for this kind of assembly.

Here's a file with my sequences. Assembly of sources 4, 8 and 12 does not work. Assembly of sources 4, 8 and 14 does work.

[RestrictionGibson.json](https://github.com/user-attachments/files/15936559/RestrictionGibson.json)

**Comment by manulera** [comment]
Hi @dgruano I see what happens here:

```
seq 12
AGCTTATCGATACCGTCGACCTCGAGGGxxGTGGCGGCCGCTCTAGAACTAGTGG
   AATAGCTATGGCAGCTGGAGCTCCCxxCACCGCCGGCGAGATCTTGATCACCTAG

seq 14
   TATCGATACCGTCGACCTCGAGGGGxxGGTGGCGGCCGCTCTAGAACTAGTG
   ATAGCTATGGCAGCTGGAGCTCCCCxxCCACCGCCGGCGAGATCTTGATCAC
```

* What should happen: because seq12 has 5' ends that the Gibson enzymes will chew, it should be treated as if it was seq 14.
* What happens: the assembly class tries to find terminal homology using the 5' overhangs

I guess the special case should be only for 5' overlaps. Will implement this in a PR and maybe you can double-check that the tests make sense?
